### ISSUE TITLE
None of mod features work on 1.21.5

### ISSUE THREAD

**Issue by kalik414** [MayaqqDev/Orbit#3]
Well, to begin with, this "honestly quite incredible mod" do nothing. Yes, exacly nothing.
When I launched my game with this mod installed, I joined singleplayer world and pressed mod key, then game just crashed..
```
Description: Unexpected error

java.lang.NoClassDefFoundError: earth/terrarium/olympus/client/components/Widgets
	at knot//dev.mayaqq.orbit.screen.OrbitMenu.<init>(OrbitMenu.kt:19)
	at knot//dev.mayaqq.orbit.Orbit.onInitializeClient$lambda$3$lambda$2(Orbit.kt:50)
	at knot//dev.mayaqq.orbit.utils.McClient.tell$lambda$0(McClient.kt:19)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1308)
	at knot//net.minecraft.class_310.method_1514(class_310.java:936)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: earth.terrarium.olympus.client.components.Widgets
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 16 more
```
Before reloading game, I opened mod `config.json`, set `buttonCount` value to `0`, and reloaded the game.
After this, I once again opened single player game, pressed mod key, but now instead of crashing, mod just shown nothing. Only thing, I could move my cursor, that pretty much all. I thoght "*maybe I need to edit something in mod configuration*", but when I tried to open one in mod menu screen, well, it showed me this:
![Image](https://github.com/user-attachments/assets/19de49ca-1b53-41bf-bb71-d294f1963327)
So, thats it. Maybe there's some mod incompleteablity, but I never used something could probably break this mod (except maybe Sodium). So, here is the list of all my mods:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          26.05.2025    11:28        1096137 appleskin-fabric-mc1.21.5-3.0.6.jar
-a---          26.05.2025    11:28          14849 BetterPingDisplay-Fabric-1.21.5-1.1.1.jar
-a---          26.05.2025    11:28         867614 bobby-5.2.7+mc1.21.5.jar
-a---          26.05.2025    11:28          63627 cherishedworlds-fabric-12.0.0+1.21.5.jar
-a---          26.05.2025    11:28        2400931 clientcommands-2.10.jar
-a---          26.05.2025    11:28        1152219 cloth-config-18.0.145-fabric.jar
-a---          26.05.2025    11:28         996045 continuity-3.0.1-test.4+1.21.5.jar
-a---          26.05.2025    11:28         192205 dynamic-fps-3.9.4+minecraft-1.21.5-fabric.jar
-a---          26.05.2025    11:28       53994439 Essential_1-3-6-2_fabric_1-21-5.jar
-a---          26.05.2025    11:28         119820 explosive-enhancement-1.3.0-1.21.4.jar
-a---          26.05.2025    11:28        2218580 fabric-api-0.124.2+1.21.5.jar
-a---          26.05.2025    11:28        7163558 fabric-language-kotlin-1.13.3+kotlin.2.1.21.jar
-a---          26.05.2025    11:28          79653 ferritecore-8.0.0-fabric.jar
-a---          26.05.2025    11:28        1145381 freecam-fabric-1.3.3+mc1.21.5.jar
-a---          26.05.2025    11:28        2142606 fzzy_config-0.6.9+1.21.5.jar
-a---          26.05.2025    11:28         230416 ImmediatelyFast-Fabric-1.9.4+1.21.5.jar
-a---          26.05.2025    11:28        2714605 iris-fabric-1.8.11+mc1.21.5.jar
-a---          26.05.2025    11:28          73837 language-reload-1.7.3+1.21.5.jar
-a---          26.05.2025    11:28         783290 lithium-fabric-0.16.2+mc1.21.5.jar
-a---          26.05.2025    11:28        1069680 modmenu-14.0.0-rc.2.jar
-a---          26.05.2025    11:28          76225 MouseTweaks-fabric-mc1.21.3-2.27.jar
-a---          26.05.2025    11:28         216075 noisium-fabric-2.6.0+mc1.21.5.jar
-a---          28.05.2025    08:48         239689 Orbit-1.0.0+1.21.5.jar
-a---          26.05.2025    11:28          96866 particle_core-0.2.6+1.21.5.jar
-a---          26.05.2025    11:28         546557 particle-rain-3.3.5.jar
-a---          26.05.2025    11:28         277765 ParticleEffects-1.0.3+1.21.5.jar
-a---          26.05.2025    11:28         257307 placeholder-api-2.6.3+1.21.5.jar
-a---          26.05.2025    11:28          81067 reeses-sodium-options-fabric-1.8.3+mc1.21.4.jar
-a---          26.05.2025    11:28         386917 shulkerboxtooltip-fabric-5.2.6+1.21.5.jar
-a---          26.05.2025    11:28         474332 skinlayers3d-fabric-1.7.5-mc1.21.5.jar
-a---          26.05.2025    11:28          73800 smoothscroll-2.2.3.1+1.21.5.jar
-a---          26.05.2025    11:28         361857 sodium-extra-fabric-0.6.3+mc1.21.5.jar
-a---          26.05.2025    11:28        1336477 sodium-fabric-0.6.13+mc1.21.5.jar
-a---          26.05.2025    11:28         204022 sound-physics-remastered-fabric-1.21.5-1.4.12.jar
-a---          26.05.2025    11:28          20447 tia-fabric-1.21.3-1.2.2.jar
-a---          26.05.2025    11:28       12656109 ViaFabricPlus-4.1.3.jar
-a---          26.05.2025    11:28          80841 visuality-0.7.10+1.21.5.jar
-a---          26.05.2025    11:28        1116615 yet_another_config_lib_v3-3.6.6+1.21.5-fabric.jar
```
Hope this help.

**Comment by Bluelix** [comment]
# Game Crashes Immediately when [Y] pressed Even With Minimal Mod Setup (MC 1.21.5)

The game crashes instantly upon pressing the designated key [Y], even when running the mod with the absolute minimum required dependencies.
## Minimal Setup Used :
- fabric-api-0.128.2+1.21.5.jar
- Fabric Language Kotlin 1.13.7+kotlin.2.2.21
- Orbit-1.0.0+1.21.5.jar

## Environment Details :
- Minecraft 1.21.5
- Fabric 0.18.2

I believe this mod could be very interesting and useful. I hope this issue can be addressed soon.
